package Forms;

import Classes.Globals;
import Classes.DBConnectionManager;
import Classes.HelperClass;
import Classes.Pozicija;
import Classes.Predstava;
import Classes.Rezervacija;
import Classes.Termin;
import java.sql.*;
import javax.swing.JOptionPane;

public class NovaRezervacija extends javax.swing.JFrame {

    Predstava predstava;
    Termin termin;
    Pozicija pozicija;
    Rezervacija rezervacija;
    
    public NovaRezervacija() {
        initComponents();

        predstava = new Predstava();
        termin = new Termin();
        pozicija = new Pozicija();
        rezervacija = new Rezervacija();
        
        predstava.fillComboPredstava(cmbPredstava);
        
        pozicija.fillComboPozicija(cmbPozicija);
        
        HelperClass.hideFields(cmbTermin, cmbPozicija, labelTermin, labelPozicija);
    }
    
    private void fillComboTermin(String predstavaNaziv) {
        int predstavaId = predstava.getPredstavaId(predstavaNaziv);
        termin.fillComboTermin(predstavaId, cmbTermin);        
    }
    
    private boolean validateForm() {
        if (!HelperClass.validateForm(cmbPredstava, cmbTermin, cmbPozicija)) {
            return false;
        }
        
        return true;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbPredstava = new javax.swing.JComboBox<>();
        labelPozicija = new javax.swing.JLabel();
        cmbPozicija = new javax.swing.JComboBox<>();
        btnReservation = new javax.swing.JButton();
        labelTermin = new javax.swing.JLabel();
        cmbTermin = new javax.swing.JComboBox<>();
        btnHome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nova rezervacija");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Izaberite predstavu");

        cmbPredstava.setName("predstavaCombo"); // NOI18N
        cmbPredstava.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbPredstavaItemStateChanged(evt);
            }
        });
        cmbPredstava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPredstavaActionPerformed(evt);
            }
        });

        labelPozicija.setText("Izaberite poziciju");

        cmbPozicija.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPozicija.setName("pozicijaCombo"); // NOI18N

        btnReservation.setText("Napravi rezervaciju");
        btnReservation.setName("btnRezervacija"); // NOI18N
        btnReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservationActionPerformed(evt);
            }
        });

        labelTermin.setText("Izaberite termin");
        labelTermin.setName("lblTermin"); // NOI18N

        cmbTermin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbTermin.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTerminItemStateChanged(evt);
            }
        });

        btnHome.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
        btnHome.setText("Natrag na pocetnu stranu");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(btnReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(44, 44, 44)
                                    .addComponent(labelPozicija))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(52, 52, 52)
                                    .addComponent(jLabel1)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelTermin))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbPozicija, 0, 160, Short.MAX_VALUE)
                            .addComponent(cmbPredstava, 0, 160, Short.MAX_VALUE)
                            .addComponent(cmbTermin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(btnHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbPredstava, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTermin)
                    .addComponent(cmbTermin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPozicija)
                    .addComponent(cmbPozicija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(btnReservation)
                .addGap(75, 75, 75))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

            
    private void btnReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservationActionPerformed
        if (!validateForm()) {
            JOptionPane.showMessageDialog(null, "Morate popuniti sva polja da biste izvrsili rezervaciju.");
            return;
        }

        String terminDate = (String)cmbTermin.getSelectedItem();
        String dateFormatted = HelperClass.formatDateToMySqlFormat(terminDate);
        String pozicijaName = (String)cmbPozicija.getSelectedItem();
        
        int idTermin = termin.getTerminId(dateFormatted);
        int idPozicija = pozicija.getPozicijaId(pozicijaName);
        int idKorisnik = Globals.loggedUserId;
              
        int brojZakazanihRezervacija = rezervacija.getNumOfReservationsForPosition(idTermin, idPozicija);
        int brojMestaPozicije = pozicija.getPositionBrojMesta(pozicijaName);
        
        if (brojZakazanihRezervacija >= brojMestaPozicije) {
            JOptionPane.showMessageDialog(null, "Za traženu poziciju \"" + pozicijaName + "\" su sva mesta popunjena. Molimo izaberite neku drugu.");
            return;
        }
        
        if(rezervacija.makeReservation(idTermin, idKorisnik, idPozicija)) {
            JOptionPane.showMessageDialog(null, "Rezervacija je uspesno napravljena.");
            HelperClass.resetForm(cmbPredstava, cmbTermin, cmbPozicija);
        }
        
    }//GEN-LAST:event_btnReservationActionPerformed

    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowOpened

    private void cmbTerminItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTerminItemStateChanged
        
    }//GEN-LAST:event_cmbTerminItemStateChanged

    private void cmbPredstavaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbPredstavaItemStateChanged
        
        if(cmbPredstava.getSelectedItem() == Globals.predstavaDefault) {
            HelperClass.hideFields(cmbTermin, cmbPozicija, labelTermin, labelPozicija);
        }
        else {
            fillComboTermin((String)cmbPredstava.getSelectedItem());
            HelperClass.showFields(cmbTermin, cmbPozicija, labelTermin, labelPozicija);
        }         
    }//GEN-LAST:event_cmbPredstavaItemStateChanged

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        dispose();
        HomePage home = new HomePage();
        home.setVisible(true);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void cmbPredstavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPredstavaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPredstavaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovaRezervacija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovaRezervacija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovaRezervacija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovaRezervacija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NovaRezervacija().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnReservation;
    private javax.swing.JComboBox<String> cmbPozicija;
    private javax.swing.JComboBox<String> cmbPredstava;
    private javax.swing.JComboBox<String> cmbTermin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelPozicija;
    private javax.swing.JLabel labelTermin;
    // End of variables declaration//GEN-END:variables
}
