
package Forms;

import Classes.DBConnectionManager;
import Classes.Globals;
import Classes.HelperClass;
import Classes.Pozicija;
import Classes.Rezervacija;
import Classes.Termin;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author arudolf
 */
public class PregledRezervacija extends javax.swing.JFrame {
    
    Rezervacija rezervacija;
    
    public PregledRezervacija() {
        initComponents();
        rezervacija = new Rezervacija();
        rezervacija.PopulateTable(tableRezervacija);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableRezervacija = new javax.swing.JTable();
        btnOtkaziRezervaciju = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableRezervacija.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableRezervacija);

        btnOtkaziRezervaciju.setText("Otkazi rezervaciju");
        btnOtkaziRezervaciju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtkaziRezervacijuActionPerformed(evt);
            }
        });

        btnHome.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
        btnHome.setText("Natrag na pocetnu stranu");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(244, Short.MAX_VALUE)
                .addComponent(btnOtkaziRezervaciju, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(173, 173, 173))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btnHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOtkaziRezervaciju)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOtkaziRezervacijuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtkaziRezervacijuActionPerformed
        if (tableRezervacija.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Molimo odaberite rezervaciju!");
            return;
        }
        
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog (null, "Da li ste sigurni da zelite da otkazete rezervaciju?", "Warning", dialogButton);
        if(dialogResult == JOptionPane.NO_OPTION){
            return;
        }
        
        int selectedRow = tableRezervacija.getSelectedRow();
        
        String pozicijaName = tableRezervacija.getValueAt(selectedRow, 2).toString();
        
        String terminDate = tableRezervacija.getValueAt(selectedRow, 1).toString();        
        //terminDate = 29-10-2021 19:05:00, mora da se prebaci u terminDate = 2021-10-29 19:05:00 pre ubacivanja u bazu
        String dateFormatted = HelperClass.formatDateToMySqlFormat(terminDate);
        
        //find termin id
        var termin = new Termin();
        int terminId = termin.getTerminId(dateFormatted);
        
        var pozicija = new Pozicija();
        int pozicijaId = pozicija.getPozicijaId(pozicijaName);

        if (termin.checkIfShowIsFinished(terminId) == true) {
            JOptionPane.showMessageDialog(null, "Ne mozete otkazati rezervaciju za predstavu koja se vec zavrsila", "Obavestenje", 1);
            return;
        }
        
        if (termin.checkIfStartsBefore24Hours(terminId) == true) {
            JOptionPane.showMessageDialog(null, "Ne mozete otkazati rezervacije za predstave koje pocinju za manje od 24h.", "Obavestenje", 2);
            return;
        }
        
        //ako ima - onda delete from reservations where termin = idtermin, idkorisnik = id, idpozicija = idpozicija
        if(rezervacija.CancelReservation(terminId, Globals.loggedUserId, pozicijaId)) {
            JOptionPane.showMessageDialog(null, "Uspesno ste otkazali rezervaciju", "Obavestenje", JOptionPane.INFORMATION_MESSAGE);
            rezervacija.PopulateTable(tableRezervacija);
        }
    }//GEN-LAST:event_btnOtkaziRezervacijuActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        dispose();
        HomePage home = new HomePage();
        home.setVisible(true);
    }//GEN-LAST:event_btnHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PregledRezervacija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PregledRezervacija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PregledRezervacija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PregledRezervacija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PregledRezervacija().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnOtkaziRezervaciju;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableRezervacija;
    // End of variables declaration//GEN-END:variables
}
